### ISSUE TITLE
Plugin does not fail on project execution failure

### ISSUE THREAD

**Issue by sverdlovka** [readyapi/readyapi-testengine-maven-plugin#3]
When the TestJob has failed on the TestEngine, the build is still marked as successful, also in the logs:

```
[INFO] ReadyAPI TestEngine Maven Plugin
[INFO] --------------------------------------
[INFO] Recipes run: 0
[INFO] Projects run: 1
[INFO] Failures: 0
```

Probably this is because currently plugin uses old report model, see in pom.xml:
```        
<dependency>
    <groupId>com.smartbear.readyapi</groupId>
     <artifactId>ready-api-testserver-client</artifactId>
     <version>1.0.0</version>
</dependency>
```

**Comment by olensmar** [comment]
thanks @sverdlovka - is there a newer report model available that we could/should use instead?

**Comment by sverdlovka** [comment]
fixed by using updated model
